import xlrd
import random
workbook = xlrd.open_workbook("library.xlsx")
worksheet = workbook.sheet_by_name("names")
skillsWorksheet = workbook.sheet_by_name("skills")
divider = "-"*78
pageBreak = '\n'*3
div_char = "-"*32+"Characteristics"+"-"*31
spacer = '      '
"""builds the library of lists used in character creation. The material is read in from library.xlsx and fed into a series of lists."""
homeworld = ['Death World','Void Born','Forge World','Hive World','Imperial World','Noble Born']
#birthright_1 = ['Scavenger','Scapegrace']
#birthright_2 = ['Scavenger','Scapegrace','Stubjack']
#birthright_3 = ['Scapegrace','Stubjack','Child of the Creed']
#birthright_4 = ['Stubjack','Child of the Creed','Savant']
#birthright_5 = ['Child of the Creed','Savant','Vaunted']
#birthright_6 = ['Savant','Vaunted']
#voidLure_1 = ['Tainted','Criminal']
#voidLure_2 = ['Tainted','Criminal','Renegade']
#voidLure_3 = ['Criminal','Renegade','Duty Bound']
#voidLure_4 = ['Renegade','Duty Bound','Zealot']
#voidLure_5 = ['Duty Bound','Zealot','Chosen of Destiny']
#voidLure_6 = ['Zealot','Chosen of Destiny']
#trials_1 = ['The Hand of war','Press-Ganged']
#trials_2 = ['The Hand of war','Press-Ganged','Calamity']
#trials_3 = ['Press-Ganged','Calamity','Ship Lorn']
#trials_4 = ['Calamity','Ship Lorn','Dark Voyage']
#trials_5 = ['Ship Lorn','Dark Voyage','High Vengetta']
#trials_6 = ['Dark Voyage','High Vengetta']
#motives_1 =['Endurance','Fortune']
#motives_2 =['Endurance','Fortune','Vengeance']
#motives_3 =['Fortune','Vengeance','Renown']
#motives_4 =['Vengeance','Renown','Pride']
#motives_6 =['Pride','Prestige']
#Career = {1:'Astropath', 2:'Arch-militant',3:'Void Master',4:'Explorator',5:'Missionary',6:'Seneschal',7:'Navigator',8:'Rogue Trader'}
HiveWorldNames = []
HumanMaleNames = []
HumanFemaleNames = []
HumanLastNames = []
HumanTitles = []
BloodAngelNames = []
BloodAngelTitles = []
DarkAngelNames = []
DarkAngelTitles = []
SpaceWolvesNames = []
SpaceWolvesTitles = []
UltramarinesNames = []
UltramarinesTitles =[]
BlackTemplarsNames = []
BlackTemplarsTitles = []
DeamonSyllabals = []
DeathWorldNames = []
VoidBornNames = []
ForgeWorldNames = []
HiveWorldNames = []
ImpWorldNames = []
NobleBornWorldNames = []
skills = []